name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Create Temporary Folder and Copy Build Files
      run: |
        mkdir temp
        cp -r build/* temp/

    - name: Switch to gh-pages Branch
      run: |
        git checkout --orphan gh-pages  # Create a new orphan branch named gh-pages
        git reset --hard  # Reset the branch to have no commit history
        git commit --allow-empty -m "Initial commit"  # Create an initial commit
        git push origin gh-pages  # Push the branch to the remote repository
        git checkout gh-pages

    - name: Copy Files to gh-pages Branch
      run: |
        cp -r temp/* .

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "harishrishee"
        git config user.email "harishrishee@gmail.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages

    - name: Provide GitHub Pages URL
      run: |
        echo "Your GitHub Pages URL: https://harishrishee.github.io/myportfolio/"

    - name: Cleanup
      run: |
        rm -rf temp

# Continue with any additional steps as needed
